version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - mkaraki
    cooldown:
      default-days: 21
      semver-major-days: 21
      semver-minor-days: 21
      semver-patch-days: 21
    groups:
      tinacms:
        patterns:
          - "@tinacms/*"
          - "tinacms"
      npm-all:
        patterns:
          - "*"
